name: CI

on: [push, workflow_dispatch]

jobs:
build:

  runs-on: windows-latest

  steps:
 - name: Download

run: Invoke WebRequest https://bin.equinox.io/c/bNyj1m0VY4c/ngrok-v3-stable-windows-amd64.zip OutFile ngrok.zip

- name: Extract

run: Expand-Archive ngrok.zip

- name: Auth

run: Angrok\ngrok.exe authtoken $Env:NGROK AUTH_TOKEN

env:

NGIDIC AUTI TOKEN: $[[ secrets.NGROK AUTH TOKEN }}

- name: Tnable TS

run: Set-itemProperty -Path "HKLM\System\CurrentControlSet\Control\terminal server-name "foeny FSConnections Value

run: Enable-NetfirewallRule -DisplayGroup "Remote Desktop"

run: Set-ItemProperty -Path "HKLM: \System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp -name "UserAuthentication" -Value 1

run: Set-Localiser Name "runneradmin" Password (ConvertTo-SecureString AsPlainText "Password!" Force)

- name: Create Tunnel

run: Angrok\ngrok.exe tcp 1389

I
