name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download
        run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1m0VY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

      - name: Extract
        run: Expand-Archive ngrok.zip -DestinationPath .

      - name: Auth
        run: .\ngrok.exe authtoken $env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Enable RDP
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 1
          net user runneradmin "Password123"

      - name: Create Tunnel
        run: .\ngrok.exe tcp 3389
